name: Docker Image CI

on:
  workflow_dispatch:

env:
  DOCKER_TAG: "latest"
  PROJECT_PATH: "/home/ubuntu/nginx/"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.AWS_PEM }}
          known_hosts: 'empty'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        id: docker_build
        run: |
          docker-compose build --pull
          docker-compose push

      - name: Build the Docker image in the aws server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ${{ env.PROJECT_PATH }}
            export DOCKER_REGISTRY=$DOCKER_REGISTRY
            export DOCKER_TAG=$DOCKER_RELEASE_IMAGE
            docker-compose stop nginx
            docker-compose rm -f
            docker-compose pull
            docker-compose up -d
            docker logout
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          privateKey: ${{ secrets.AWS_PEM }}
